import { Component, ViewEncapsulation } from "@angular/core";
import { EnrollService } from "./services/enroll.service";

@Component({
  selector: "app-root",
  templateUrl: "./app.component.html",
  styleUrls: ["./app.component.css"],
  // providers: [EnrollService],
})
export class AppComponent {
  title = "AllPractice";

  // constructor(public enrollService: EnrollService) {}

  users = [
    {
      id: 1,
      firstName: "Terry",
      lastName: "Medhurst",
      maidenName: "Smitham",
      age: 50,
      gender: "male",
      email: "atuny0@sohu.com",
      username: "atuny0",
    },
    {
      id: 2,
      firstName: "Sheldon",
      lastName: "Quigley",
      maidenName: "Cole",
      age: 28,
      gender: "male",
      email: "hbingley1@plala.or.jp",
      username: "hbingley1",
    },
    {
      id: 3,
      firstName: "Terrill",
      lastName: "Hills",
      maidenName: "Hoeger",
      age: 38,
      gender: "male",
      email: "rshawe2@51.la",
      username: "rshawe2",
    },
    {
      id: 4,
      firstName: "Miles",
      lastName: "Cummerata",
      maidenName: "Maggio",
      age: 49,
      gender: "male",
      email: "yraigatt3@nature.com",
      username: "yraigatt3",
    },
    {
      id: 5,
      firstName: "Mavis",
      lastName: "Schultz",
      maidenName: "Yundt",
      age: 38,
      gender: "male",
      email: "kmeus4@upenn.edu",
      username: "kmeus4",
    },
    {
      id: 6,
      firstName: "Alison",
      lastName: "Reichert",
      maidenName: "Franecki",
      age: 21,
      gender: "female",
      email: "jtreleven5@nhs.uk",
      username: "jtreleven5",
    },
    {
      id: 7,
      firstName: "Oleta",
      lastName: "Abbott",
      maidenName: "Wyman",
      age: 31,
      gender: "female",
      email: "dpettegre6@columbia.edu",
      username: "dpettegre6",
    },
    {
      id: 8,
      firstName: "Ewell",
      lastName: "Mueller",
      maidenName: "Durgan",
      age: 29,
      gender: "male",
      email: "ggude7@chron.com",
      username: "ggude7",
    },
    {
      id: 9,
      firstName: "Demetrius",
      lastName: "Corkery",
      maidenName: "Gleason",
      age: 22,
      gender: "male",
      email: "nloiterton8@aol.com",
      username: "nloiterton8",
    },
    {
      id: 10,
      firstName: "Eleanora",
      lastName: "Price",
      maidenName: "Cummings",
      age: 37,
      gender: "female",
      email: "umcgourty9@jalbum.net",
      username: "umcgourty9",
    },
    {
      id: 11,
      firstName: "Marcel",
      lastName: "Jones",
      maidenName: "Smith",
      age: 39,
      gender: "male",
      email: "acharlota@liveinternet.ru",
      username: "acharlota",
    },
    {
      id: 12,
      firstName: "Assunta",
      lastName: "Rath",
      maidenName: "Heller",
      age: 42,
      gender: "female",
      email: "rhallawellb@dropbox.com",
      username: "rhallawellb",
    },
    {
      id: 13,
      firstName: "Trace",
      lastName: "Douglas",
      maidenName: "Lemke",
      age: 26,
      gender: "male",
      email: "lgribbinc@posterous.com",
      username: "lgribbinc",
    },
    {
      id: 14,
      firstName: "Enoch",
      lastName: "Lynch",
      maidenName: "Heidenreich",
      age: 21,
      gender: "male",
      email: "mturleyd@tumblr.com",
      username: "mturleyd",
    },
    {
      id: 15,
      firstName: "Jeanne",
      lastName: "Halvorson",
      maidenName: "Cummerata",
      age: 26,
      gender: "female",
      email: "kminchelle@qq.com",
      username: "kminchelle",
    },
    {
      id: 16,
      firstName: "Trycia",
      lastName: "Fadel",
      maidenName: "Rosenbaum",
      age: 41,
      gender: "female",
      email: "dpierrof@vimeo.com",
      username: "dpierrof",
    },
    {
      id: 17,
      firstName: "Bradford",
      lastName: "Prohaska",
      maidenName: "Bins",
      age: 43,
      gender: "male",
      email: "vcholdcroftg@ucoz.com",
      username: "vcholdcroftg",
    },
    {
      id: 18,
      firstName: "Arely",
      lastName: "Skiles",
      maidenName: "Monahan",
      age: 42,
      gender: "male",
      email: "sberminghamh@chron.com",
      username: "sberminghamh",
    },
    {
      id: 19,
      firstName: "Gust",
      lastName: "Purdy",
      maidenName: "Abshire",
      age: 46,
      gender: "male",
      email: "bleveragei@so-net.ne.jp",
      username: "bleveragei",
    },
    {
      id: 20,
      firstName: "Lenna",
      lastName: "Renner",
      maidenName: "Schumm",
      age: 41,
      gender: "female",
      email: "aeatockj@psu.edu",
      username: "aeatockj",
    },
    {
      id: 21,
      firstName: "Doyle",
      lastName: "Ernser",
      maidenName: "Feeney",
      age: 23,
      gender: "male",
      email: "ckensleyk@pen.io",
      username: "ckensleyk",
    },
    {
      id: 22,
      firstName: "Tressa",
      lastName: "Weber",
      maidenName: "Williamson",
      age: 41,
      gender: "female",
      email: "froachel@howstuffworks.com",
      username: "froachel",
    },
    {
      id: 23,
      firstName: "Felicity",
      lastName: "O'Reilly",
      maidenName: "Rosenbaum",
      age: 46,
      gender: "female",
      email: "beykelhofm@wikispaces.com",
      username: "beykelhofm",
    },
    {
      id: 24,
      firstName: "Jocelyn",
      lastName: "Schuster",
      maidenName: "Dooley",
      age: 19,
      gender: "male",
      email: "brickeardn@fema.gov",
      username: "brickeardn",
    },
    {
      id: 25,
      firstName: "Edwina",
      lastName: "Ernser",
      maidenName: "Kiehn",
      age: 21,
      gender: "female",
      email: "dfundello@amazon.co.jp",
      username: "dfundello",
    },
    {
      id: 26,
      firstName: "Griffin",
      lastName: "Braun",
      maidenName: "Deckow",
      age: 35,
      gender: "male",
      email: "lgronaverp@cornell.edu",
      username: "lgronaverp",
    },
    {
      id: 27,
      firstName: "Piper",
      lastName: "Schowalter",
      maidenName: "Wuckert",
      age: 47,
      gender: "female",
      email: "fokillq@amazon.co.jp",
      username: "fokillq",
    },
    {
      id: 28,
      firstName: "Kody",
      lastName: "Terry",
      maidenName: "Larkin",
      age: 28,
      gender: "male",
      email: "xisherwoodr@ask.com",
      username: "xisherwoodr",
    },
    {
      id: 29,
      firstName: "Macy",
      lastName: "Greenfelder",
      maidenName: "Koepp",
      age: 45,
      gender: "female",
      email: "jissetts@hostgator.com",
      username: "jissetts",
    },
    {
      id: 30,
      firstName: "Maurine",
      lastName: "Stracke",
      maidenName: "Abshire",
      age: 31,
      gender: "female",
      email: "kdulyt@umich.edu",
      username: "kdulyt",
    },
  ];

  display: boolean = false;

  displayNotice() {
    this.display = !this.display;
  }

  occupation: string = "lawyer1";
}
